spring:

  application:

    name: spring-cloud-gateway-app

  cloud:

    gateway:

      routes:

        - id: helloservice-route

          uri: http://localhost:8071

          predicates:

            - Path=/rest/service/factorial/{num}/**
            
            
management:

  endpoints:

    web:

      exposure:

        include: "*"

  endpoint:

    health:

      show-details: always

    gateway:

      enabled: true
       
server:
  port: 8070
  